Revert "Fix fallen allies calculation for Kowtow Cleave and Retaliate abilities (#2542)"
app/core/abilities/abilities.ts:8019:40 - error TS2304: Cannot find name 'nbAlliesAlive'.

This reverts commit ca47d171aa52b08acc74f4075177a088bee419c2.