Remove Hitmonchan bot from botv2.json
Removes the bot that causes this error

ValidationError: botV2 validation failed: steps.18.board.4.name: MEGA_MEDICHAM is not a valid enum value for path name., steps.19.board.4.name: MEGA_MEDICHAM is not a valid enum value for path name.
    at Document.invalidate (/home/heel/pokemonAutoChess/node_modules/mongoose/lib/document.js:3318:32)
    at Subdocument.invalidate (/home/heel/pokemonAutoChess/node_modules/mongoose/lib/types/subdocument.js:229:12)
    at Subdocument.invalidate (/home/heel/pokemonAutoChess/node_modules/mongoose/lib/types/subdocument.js:229:12)
    at /home/heel/pokemonAutoChess/node_modules/mongoose/lib/document.js:3079:17
    at /home/heel/pokemonAutoChess/node_modules/mongoose/lib/schemaType.js:1388:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)